sudo: false

language: node_js

node_js:
  - node

services:
  - mongodb
  
before_script:
  #- npm run-script generate
  #- npm start &
  #- sleep 15

deploy:
  provider: heroku
  api_key:
    secure: 80c9ef0c-007b-4056-ad77-6b64d0f353af
  app: firm-vote
  run:
    - restart
    - "rake cleanup"